config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root to: 'forex#index'
  resources :posts, only: %i[new create index]

  scope :forex do
    get '/', to: 'forex#index'
    get '/pair', to: 'forex#show'
    get '/convert', to: 'forex#convert'
  end

  get '*path', to: 'application#render_404'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/currency.rb
class Currency < ApplicationRecord
  validates :pair, presence: true, length: { is: 6 }
  validates :rate, presence: true, numericality: true
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def render_404
      render file: "#{Rails.root}/public/404.html", status: :not_found
    end
end

app/controllers/forex_controller.rb
require_relative '../services/forex_service/forex_list'
require_relative '../services/forex_service/forex_pair'
require_relative '../services/forex_service/forex_converter'

class ForexController < ApplicationController
  include Forex

  def index
    @currency_pairs = ForexList.call
  end

  def show
    @pair = params[:pairs]
    currency_data = ForexPair.call(@pair)

    currency_data[:error] ? flash[:error] = currency_data[:error] : @currency = currency_data[:currency]
  end

  def convert
    conversion = ForexConverter.call(params[:from], params[:to], params[:amount])

    conversion[:error] ? flash[:error] = conversion[:error] : @conversion = conversion[:conversion]
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.build(post_params)

    if @post.save
      redirect_to posts_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def index
    @posts = Post.all
  end

  private

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forex_helper.rb
module ForexHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/forex/convert.html.erb
<h1>Currency Converter</h1>

<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% end %>

<% if @conversion %>
<%= form_tag convert_url, method: :get do %>
  <%= label_tag :from, 'From:' %>
  <%= text_field_tag :from, params[:from] %>

  <%= label_tag :to, 'To:' %>
  <%= text_field_tag :to, params[:to] %>

  <%= label_tag :amount, 'Amount:' %>
  <%= text_field_tag :amount, params[:amount] %>

  <%= submit_tag 'Convert' %>
<% end %>

  <p><%= params[:amount] %> <%= params[:from] %> = <%= @conversion %> <%= params[:to] %></p>
<% end %>

<%= link_to 'Back', root_path %>

app/views/forex/index.html.erb
<h1>Available currency pairs</h1>

<ol>
  <% @currency_pairs.each do |pair| %>
    <li>
      <%= link_to pair, "/forex/pair?pairs=#{pair}" %> 
    </li>
  <% end %>
</ol>
  

app/views/forex/show.html.erb
<h1>Currency pair: <%= @pair %></h1>

<% if flash[:error] %>
  <p><%= flash[:error] %></p>
<% else %>
  <p>Current rate: <%= @currency.rate %></p>  
<% end %>

<%= link_to 'Back', root_path %>
<%= link_to 'Convert', "/forex/convert?from=#{@pair.to_s[0..2]}&to=#{@pair.to_s[3..5]}&amount=1" %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MembersOnly</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/posts/create.html.erb
<h1>Posts#create</h1>
<p>Find me in app/views/posts/create.html.erb</p>

app/views/posts/index.html.erb
<h1>Posts</h1>

<% @posts.each do |post| %>
  <h3>Title: <%= post.title %></h3>

  <% if user_signed_in? %>
    <h4>Author: <%= post.user.email %></h4>
  <% end %> 

  <p><%= post.body %></p>
<% end %>

app/views/posts/new.html.erb
<h1>New post</h1>

<%= form_with model: @post, url: posts_path do |form| %>
  <%= form.label :title %>
  <%= form.text_field :title %>

  <%= form.label :body %>
  <%= form.text_area :body %>

  <%= form.submit %>
<% end %>

<%= button_to(
        "Log Out",
        destroy_user_session_path,
        method: :delete
      ) %>